### ISSUE TITLE
[bug] cannot change directory if target doesn't exist

### ISSUE THREAD

**Issue by UpcraftLP** [danya02/minecraft-file-extractor#1]
If the specified output directory doesn't exist, the program is unable to change directory.

solution is to check if the directory exists and create it if necessary...

**Comment by danya02** [comment]
Yes, it is so. When I wrote this, I thought that you wouldn't want the directory to be created in case you actually mistyped it. Didn't realize normally users expect the directory to be created.

**Comment by danya02** [comment]
Sidenote: I'm surprised anyone could find this repo, as the program is used for a rather obscure goal.

**Comment by UpcraftLP** [comment]
> Sidenote: I'm surprised anyone could find this repo, as the program is used for a rather obscure goal.

Haha yeah, used it to extract the april fools textures into a resource pack, worked quite well ^^
